import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../../components/layout/header";
import Footer from "../../components/layout/footer";
import RecoilRootWrapper from "../../wrappers/RecoilRootWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="ko">
        <head>
            <title>Rhythm Archive</title>
        </head>
        
        <body 
            className={inter.className}
        >
            <Header />
            <div className={``}>
            <RecoilRootWrapper>
                {children}
            </RecoilRootWrapper>
            </div>
            <Footer />
        </body>
        </html>
    );
}
